version: '3'

services:
  moviedbfrontend:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 3001:3000
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:3000